# Generated by Django 4.2.28 on 2026-02-05 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting feedback', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the person submitting feedback', max_length=254)),
                ('message', models.TextField(help_text='Feedback message content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the feedback was submitted')),
                ('read', models.BooleanField(default=False, help_text='Whether an admin has marked this feedback as read')),
                ('user', models.ForeignKey(blank=True, help_text='The user who submitted the feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
