import { Link } from "react-router-dom";
import React from "react";

export default function Home() {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        Quickly use the links below to navigate through all pages
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home" style={{ color: "lightblue" }}>
            HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/another-page" style={{ color: "lightblue" }}>
            Another Page
          </Link>
        </li>
      </ul>
      <p>src/pages/Home.tsx</p>
      <p>This project was generated by Dhiwise</p>
    </div>
  );
}
