# Generated by Django 4.2.7 on 2024-11-06 15:58

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the organization.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the dashboard.', primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, help_text='Configuration settings for the dashboard stored in JSON format.', null=True)),
                ('privacy_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='private', help_text='Privacy level of the dashboard.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this dashboard was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this dashboard was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups that have access to this dashboard.', related_name='dashboards', to='auth.group')),
                ('organisations', models.ManyToManyField(blank=True, help_text='Organisations associated with this dashboard.', related_name='dashboards', to='dashboard.organisation')),
                ('users', models.ManyToManyField(blank=True, help_text='Users who have access to this dashboard.', related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
    ]
