# Generated by Django 4.2.7 on 2024-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='organisations',
            field=models.ManyToManyField(blank=True, help_text='Organisations associated with this dashboard.', related_name='dashboards', to='base.organisation'),
        ),
    ]
