# Generated by Django 4.2.23 on 2025-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dashboard_metadata_alter_dashboard_analysis_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image of the landscape.', null=True, upload_to='dashboard/thumbnails/'),
        ),
    ]
