# Generated by Django 4.2.15 on 2024-11-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.ForeignKey(blank=True, help_text='The type of issue for the ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='support.issuetype'),
        ),
    ]
