# Generated by Django 4.2.7 on 2024-11-06 16:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the intervention area.', max_length=255, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='The spatial geometry of the intervention area.', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this intervention area was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this intervention area was last updated.')),
            ],
            options={
                'verbose_name': 'Intervention Area',
                'verbose_name_plural': 'Intervention Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the analysis.', primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('spatial', 'Spatial'), ('temporal', 'Temporal'), ('statistical', 'Statistical')], default='spatial', help_text='Type of analysis performed.', max_length=20)),
                ('temporal_resolution', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='The temporal resolution of the analysis, if applicable.', max_length=20, null=True)),
                ('reference_period_start', models.DateField(blank=True, help_text='The start date for the reference period of the analysis.')),
                ('reference_period_end', models.DateField(blank=True, help_text='The end date for the reference period of the analysis.')),
                ('comparison_period_start', models.DateField(blank=True, help_text='The start date for the comparison period of the analysis.')),
                ('comparison_period_end', models.DateField(blank=True, help_text='The end date for the comparison period of the analysis.')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='The spatial geometry of the analysis (e.g., area of interest).', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this analysis was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this analysis was last updated.')),
                ('created_by', models.ForeignKey(help_text='User who created this analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analyses', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, help_text='The indicator being analyzed.', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='alerts.indicator')),
                ('intervention_area', models.ForeignKey(blank=True, help_text='The intervention area associated with this analysis.', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis.interventionarea')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
