# Generated by Django 4.2.15 on 2024-12-06 05:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_landscape'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landscape',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='landscape',
            name='project_name',
            field=models.CharField(blank=True, help_text='The name of the project.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LandscapeCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(help_text='The id of the community that coming from GEE.', max_length=256, unique=True)),
                ('community_name', models.CharField(blank=True, help_text='The name of the community.', max_length=256, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='Geometry of community.', srid=4326)),
                ('landscape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.landscape')),
            ],
            options={
                'verbose_name_plural': 'Landscape Communities',
                'db_table': 'analysis_landscape_community',
            },
        ),
    ]
