# Generated by Django 4.2.15 on 2025-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_useranalysisresults_analysis_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalysisresults',
            name='raster_output_path',
            field=models.CharField(blank=True, help_text='Path to the raster output of this analysis.', max_length=512, null=True),
        ),
    ]
