# Generated by Django 4.2.15 on 2025-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_useranalysisresults_analysis_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEEAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key to the asset.', max_length=50)),
                ('source', models.CharField(help_text='Source path to the asset.', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'GEE Assets',
                'db_table': 'analysis_gee_asset',
            },
        ),
    ]
