# Generated by Django 4.2.19 on 2025-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_geeasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalysisresults',
            name='raster_output_path',
            field=models.CharField(blank=True, help_text='Path to the raster output of this analysis.', max_length=512, null=True),
        ),
    ]
