# Generated by Django 4.2.19 on 2025-02-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_useranalysisresults_raster_output_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeasset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Asset metadata.', null=True),
        ),
    ]
