# Generated by Django 4.2.19 on 2025-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_useranalysisresults_raster_output_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResultsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_results', models.JSONField(blank=True, null=True)),
                ('analysis_inputs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
