# Generated by Django 4.2.20 on 2025-03-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0010_analysisrasteroutput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_inputs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', help_text='Status of the analysis task.', max_length=50)),
                ('task_id', models.CharField(blank=True, help_text='ID of the task.', max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the task was completed.', null=True)),
                ('result', models.JSONField(blank=True, help_text='Result of the analysis task.', null=True)),
                ('error', models.JSONField(blank=True, help_text='Error message if the task failed.', null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
