# Generated by Django 4.2.20 on 2025-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_analysistask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project.', max_length=512, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='landscape',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='The projects associated with this landscape.', related_name='landscapes', to='analysis.project'),
        ),
    ]
