# Generated by Django 4.2.21 on 2025-05-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_project_landscape_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalysisresults',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the analysis result.', null=True),
        ),
        migrations.AddField(
            model_name='useranalysisresults',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the analysis result.', max_length=255, null=True),
        ),
    ]
