# Generated by Django 4.2.23 on 2025-08-06 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0014_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description of the indicator.', null=True)),
                ('variable_name', models.CharField(help_text='The variable name used in the analysis.', max_length=255, unique=True)),
                ('source', models.CharField(choices=[('base', 'Base'), ('GPW', 'Global Pasteur Watch'), ('other', 'Other')], default='base', help_text='The source of the indicator.', max_length=50)),
                ('analysis_types', models.JSONField(blank=True, default=list, help_text='List of analysis types this indicator can be used for.', null=True)),
                ('temporal_resolutions', models.JSONField(blank=True, default=list, help_text='List of temporal resolutions this indicator can be used for.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the indicator.', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration for the indicator.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the indicator is active.')),
                ('name', models.CharField(help_text='The name of the indicator.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='UserGEEAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source path to the asset.', max_length=512)),
                ('type', models.CharField(choices=[('image', 'image'), ('image_collection', 'image_collection'), ('table', 'table'), ('classifier', 'classifier'), ('feature_view', 'feature_view'), ('folder', 'folder')], help_text='Asset type.', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Asset metadata.', null=True)),
                ('key', models.CharField(help_text='Key to the asset.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gee_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User GEE Assets',
                'db_table': 'analysis_user_gee_asset',
                'unique_together': {('key', 'created_by')},
            },
        ),
    ]
