# Generated by Django 4.2.23 on 2025-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_userindicator_usergeeasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userindicator',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userindicator',
            name='variable_name',
            field=models.CharField(help_text='The variable name used in the analysis.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='userindicator',
            constraint=models.UniqueConstraint(fields=('name', 'variable_name', 'created_by'), name='unique_user_indicator'),
        ),
    ]
