# Generated by Django 4.2.23 on 2025-09-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_userindicator_usergeeasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userindicator',
            name='ingestion_task_error',
            field=models.TextField(blank=True, help_text='Any error messages from the GEE ingestion task.', null=True),
        ),
        migrations.AddField(
            model_name='userindicator',
            name='ingestion_task_id',
            field=models.TextField(blank=True, help_text='The task ID for the GEE ingestion task.', null=True),
        ),
    ]
