# Generated by Django 4.2.23 on 2025-09-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_userindicator_usergeeasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeeasset',
            name='ingestion_status',
            field=models.JSONField(blank=True, default=dict, help_text='The status of GEE ingestion task.', null=True),
        ),
    ]
