# Generated by Django 4.2.23 on 2025-09-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_alter_userindicator_unique_together_and_more'),
        ('analysis', '0016_usergeeasset_ingestion_status'),
    ]

    operations = [
    ]
