# Generated by Django 4.2.30 on 2026-05-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_merge_20250909_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(choices=[('base', 'Base'), ('GPW', 'Global Pasteur Watch'), ('trends-earth', 'Trends.Earth'), ('other', 'Other')], default='base', help_text='The source of the indicator.', max_length=50),
        ),
        migrations.AlterField(
            model_name='userindicator',
            name='source',
            field=models.CharField(choices=[('base', 'Base'), ('GPW', 'Global Pasteur Watch'), ('trends-earth', 'Trends.Earth'), ('other', 'Other')], default='base', help_text='The source of the indicator.', max_length=50),
        ),
    ]
