# Generated by Django 4.2.28 on 2026-03-05 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0017_merge_20250909_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysistask',
            options={'verbose_name': 'Analysis Task', 'verbose_name_plural': 'Analysis Tasks'},
        ),
        migrations.AddField(
            model_name='analysistask',
            name='source',
            field=models.CharField(choices=[('gee', 'Google Earth Engine'), ('trends_earth', 'Trends.Earth')], default='gee', help_text='Backend that processes this task.', max_length=20),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='task_type',
            field=models.CharField(choices=[('ldn', 'Land Degradation Neutrality (SDG 15.3.1)'), ('drought', 'Drought'), ('urbanization', 'Sustainable Urbanization (SDG 11.3.1)'), ('population', 'Population')], default='ldn', help_text='Type of Trends.Earth analysis (only relevant when source=trends_earth).', max_length=20),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='te_execution_id',
            field=models.CharField(blank=True, help_text='Trends.Earth execution ID (populated when source=trends_earth).', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TrendsEarthSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Trends.Earth account email address.', max_length=254)),
                ('refresh_token', models.TextField(blank=True, help_text='Long-lived Trends.Earth refresh token. Populated after first successful authentication.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this setting was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this setting was last updated.')),
                ('user', models.OneToOneField(help_text='The ARW user who owns these credentials.', on_delete=django.db.models.deletion.CASCADE, related_name='trends_earth_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trends.Earth Setting',
                'verbose_name_plural': 'Trends.Earth Settings',
            },
        ),
    ]
