# Generated by Django 4.2.7 on 2024-11-05 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the alert setting.', max_length=100)),
                ('enable_alert', models.BooleanField(default=False, help_text='Indicates if the alert is enabled.')),
                ('last_alert', models.DateTimeField(blank=True, help_text='Timestamp of the last triggered alert.', null=True)),
                ('threshold_comparison', models.FloatField(default=0, help_text='Value for comparison to trigger an alert if exceeded.')),
                ('threshold_value', models.FloatField(default=0, help_text='Threshold value to trigger the alert.')),
                ('anomaly_detection_alert', models.BooleanField(default=False, help_text='Enable to trigger alerts for detected anomalies.')),
                ('email_alert', models.BooleanField(default=False, help_text='Send alert notifications via email.')),
                ('in_app_alert', models.BooleanField(default=False, help_text='Enable in-app alert notifications.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this alert setting was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this alert setting was last updated.')),
            ],
            options={
                'verbose_name': 'Alert Setting',
                'verbose_name_plural': 'Alert Settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the indicator.', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorAlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='The text of the indicator alert history.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this alert history entry was created.')),
                ('alert_setting', models.ForeignKey(help_text='The alert setting associated with this alert history.', on_delete=django.db.models.deletion.CASCADE, related_name='alert_histories', to='alerts.alertsetting')),
            ],
            options={
                'verbose_name': 'Indicator Alert History',
                'verbose_name_plural': 'Indicator Alert Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.indicator'),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='user',
            field=models.ForeignKey(help_text='The user associated with this alert setting.', on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
