# Generated by Django 4.2.20 on 2025-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertsetting_location'),
        ('alerts', '0002_notificationreadstatus'),
    ]

    operations = [
    ]
