# Generated by Django 4.2.20 on 2025-05-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_project_landscape_projects'),
        ('alerts', '0002_notificationreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location to which this alert applies.', null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.landscapecommunity'),
        ),
    ]
