# Generated by Django 4.2.23 on 2025-06-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertsetting_analysis_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='running_interval',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], default='Monthly'),
        ),
    ]
