# Generated by Django 4.2.21 on 2025-05-28 05:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('earthranger', '0002_earthrangerevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthrangerevents',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='earthrangerevents',
            name='name',
        ),
        migrations.AddField(
            model_name='earthrangerevents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='earthrangerevents',
            name='earth_ranger_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earthrangerevents',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
