# Generated by Django 4.2.23 on 2025-07-18 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('earthranger', '0003_rename_last_updated_earthrangerevents_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apischedule',
            name='run_every_minutes',
            field=models.IntegerField(blank=True, choices=[(5, 'Every 5 minutes'), (1440, 'Every day'), (10080, 'Every week'), (43200, 'Every month'), (0, 'Stop Scheduling')], help_text='Select a predefined schedule or leave blank to set a custom interval.', null=True),
        ),
        migrations.CreateModel(
            name='EarthRangerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earthranger_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='earthrangerevents',
            name='earth_ranger_settings',
            field=models.ManyToManyField(related_name='events', to='earthranger.earthrangersetting'),
        ),
    ]
