# Generated by Django 4.2.29 on 2026-04-18 00:02

from django.db import migrations, models


def populate_event_type(apps, schema_editor):
    EarthRangerEvents = apps.get_model('earthranger', 'EarthRangerEvents')
    for event in EarthRangerEvents.objects.exclude(data={}).iterator():
        event_type = event.data.get('event_type', '')
        event_category = event.data.get('event_category', '')
        if event_type:
            EarthRangerEvents.objects.filter(pk=event.pk).update(
                event_type=event_type,
                event_category=event_category
            )


class Migration(migrations.Migration):

    dependencies = [
        ('earthranger', '0004_alter_apischedule_run_every_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthrangerevents',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='earthrangerevents',
            name='event_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(
            populate_event_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
