# Generated by Django 4.2.29 on 2026-04-29 06:57

from django.db import migrations, models
from django.utils.dateparse import parse_datetime


def populate_event_time(apps, _schema_editor):
    EarthRangerEvents = apps.get_model('earthranger', 'EarthRangerEvents')
    for event in EarthRangerEvents.objects.exclude(data={}).iterator():
        time_str = event.data.get('time', '') or ''
        event_time = parse_datetime(time_str) if time_str else None
        if event_time:
            EarthRangerEvents.objects.filter(pk=event.pk).update(
                event_time=event_time
            )


class Migration(migrations.Migration):

    dependencies = [
        ('earthranger', '0005_earthrangerevents_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthrangerevents',
            name='event_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When the event occurred, sourced from the 'time' field in the EarthRanger API response.", null=True),
        ),
        migrations.RunPython(
            populate_event_time,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
