# Generated by Django 4.2.28 on 2026-03-13 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendsEarthSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Trends.Earth account email address.', max_length=254)),
                ('refresh_token', models.TextField(blank=True, help_text='Long-lived Trends.Earth refresh token. Populated after first successful authentication.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this setting was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this setting was last updated.')),
                ('user', models.OneToOneField(help_text='The ARW user who owns these credentials.', on_delete=django.db.models.deletion.CASCADE, related_name='trends_earth_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trends.Earth Setting',
                'verbose_name_plural': 'Trends.Earth Settings',
            },
        ),
        migrations.CreateModel(
            name='TrendsEarthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(blank=True, help_text='Trends.Earth execution ID.', max_length=255, null=True)),
                ('job_type', models.CharField(choices=[('ldn', 'Land Degradation Neutrality (SDG 15.3.1)'), ('drought', 'Drought'), ('urbanization', 'Sustainable Urbanization (SDG 11.3.1)'), ('population', 'Population')], help_text='Type of Trends.Earth analysis.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the job.', max_length=20)),
                ('geojson', models.JSONField(blank=True, help_text='GeoJSON geometry for the area of interest.', null=True)),
                ('year_initial', models.IntegerField(blank=True, help_text='Initial year for the analysis.', null=True)),
                ('year_final', models.IntegerField(blank=True, help_text='Final year for the analysis.', null=True)),
                ('task_name', models.CharField(blank=True, help_text='Name of the task submitted to Trends.Earth.', max_length=255)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Result data from Trends.Earth upon completion.')),
                ('error', models.JSONField(blank=True, default=dict, help_text='Error information if the job failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the job was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the job was last updated.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the job completed.', null=True)),
                ('user', models.ForeignKey(help_text='The user who submitted this job.', on_delete=django.db.models.deletion.CASCADE, related_name='trends_earth_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trends.Earth Job',
                'verbose_name_plural': 'Trends.Earth Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
