# Generated by Django 4.2.7 on 2024-11-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0004_auto_20230328_1430"),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationInvitation",
            fields=[
                (
                    "invitation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="invitations.invitation",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="base.organisation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("invitations.invitation",),
        ),
    ]
