# Generated by Django 4.2.15 on 2024-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_organisationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_support_staff',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a support staff member.'),
        ),
    ]
