# Generated by Django 4.2.15 on 2024-11-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_is_support_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationinvitation',
            name='metadata',
            field=models.TextField(blank=True, help_text='Additional metadata for the request (JSON format).', null=True),
        ),
        migrations.AddField(
            model_name='organisationinvitation',
            name='request_type',
            field=models.CharField(choices=[('add_organisation', 'Add Organisation'), ('join_organisation', 'Join Organisation')], default='add_organisation', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisationinvitation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_invitations', to='base.organisation'),
        ),
    ]
