# Generated by Django 4.2.15 on 2024-12-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_userprofile_organisation_userorganisations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AlterUniqueTogether(
            name='userorganisations',
            unique_together={('user_profile', 'organisation')},
        ),
        migrations.RemoveField(
            model_name='userorganisations',
            name='user',
        ),
    ]
