# Generated by Django 4.2.15 on 2025-01-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationInvitationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceepted', models.BooleanField(default=False)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base.organisationinvitation')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_details', to='base.organisation')),
            ],
            options={
                'unique_together': {('invitation', 'organisation')},
            },
        ),
    ]
