# Generated by Django 4.2.15 on 2025-01-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_organisationinvitationdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationinvitationdetail',
            old_name='aceepted',
            new_name='accepted',
        ),
    ]
