# Generated by Django 4.2.15 on 2025-01-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_aceepted_organisationinvitationdetail_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationinvitation',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='organisationinvitation',
            name='request_type',
        ),
        migrations.AddField(
            model_name='organisationinvitationdetail',
            name='metadata',
            field=models.TextField(blank=True, help_text='Additional metadata for the request (JSON format).', null=True),
        ),
        migrations.AddField(
            model_name='organisationinvitationdetail',
            name='request_type',
            field=models.CharField(choices=[('add_organisation', 'Add Organisation'), ('join_organisation', 'Join Organisation')], default='add_organisation', max_length=20),
        ),
    ]
