# Generated by Django 4.2.15 on 2025-01-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_organisationinvitation_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationinvitationdetail',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_details', to='base.organisation'),
        ),
    ]
