# Generated by Django 4.2.15 on 2025-01-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_organisationinvitationdetail_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationinvitationdetail',
            name='invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base.organisationinvitation'),
        ),
    ]
