# Generated by Django 4.2.19 on 2025-03-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0002_layergrouptype_inputlayer_metadata_inputlayer_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('geojson', 'geojson'), ('shapefile', 'shapefile'), ('geopackage', 'geopackage'), ('kml', 'kml')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('file', models.FileField(blank=True, help_text='Exported file.', null=True, upload_to='exported_files/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('layers', models.ManyToManyField(related_name='export_requests', to='layers.inputlayer')),
                ('requested_by', models.ForeignKey(help_text='User who submits the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
