# Generated by Django 4.2.20 on 2025-04-23 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0003_exportlayerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLayerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, help_text='API or file endpoint URL', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fetch_type', models.CharField(choices=[('api', 'API'), ('file', 'File URL'), ('gee', 'Google Earth Engine'), ('manual', 'Manual Upload')], default='manual', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional custom fetch options like band, CRS, token...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='layers.dataprovider')),
            ],
            options={
                'verbose_name': 'External Layer Source',
                'verbose_name_plural': 'External Layer Sources',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLayer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('raster', 'Raster'), ('vector', 'Vector'), ('json', 'JSON')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('file', models.FileField(blank=True, help_text='GeoTIFF, CSV, or JSON file for this layer.', null=True, upload_to='external_layers/files/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_auto_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_layers', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, help_text='The dataset source this layer came from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_layers', to='layers.externallayersource')),
            ],
            options={
                'verbose_name': 'External Layer',
                'verbose_name_plural': 'External Layers',
                'ordering': ['-created_at'],
            },
        ),
    ]
