# Generated by Django 4.2.20 on 2025-05-14 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_exportlayerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedCog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscape_id', models.CharField(max_length=100)),
                ('gdrive_file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('input_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.inputlayer')),
            ],
        ),
    ]
