# Generated by Django 4.2.20 on 2025-04-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_externallayersource_externallayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.externallayersource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
