# Generated by Django 4.2.20 on 2025-05-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_exportedcog'),
        ('layers', '0004_externallayersource_fetchhistory_externallayer'),
    ]

    operations = [
    ]
