# Generated by Django 4.2.21 on 2025-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_merge_20250529_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallayersource',
            name='slug',
            field=models.SlugField(help_text="Short unique identifier for this data source (e.g., 'wri')", max_length=100, unique=True),
        ),
    ]
