# Generated by Django 4.2.23 on 2025-10-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_alter_externallayersource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedcog',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the export task completed.', null=True),
        ),
        migrations.AddField(
            model_name='exportedcog',
            name='errors',
            field=models.TextField(blank=True, help_text='Error messages if the export failed.', null=True),
        ),
        migrations.AddField(
            model_name='exportedcog',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the export task started.', null=True),
        ),
        migrations.AddField(
            model_name='exportedcog',
            name='status',
            field=models.CharField(blank=True, help_text='Status message from the export operation.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportedcog',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking the export task.', max_length=255, null=True),
        ),
    ]
