# Generated by Django 4.2.15 on 2024-11-20 15:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_initial_bound', models.JSONField(blank=True, default=core.models.default_map_initial_bound, help_text='Map initial bound')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
