# Generated by Django 4.2.15 on 2024-12-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='worker_layer_api_key',
            field=models.TextField(blank=True, help_text='API Key that is used by worker to upload pmtiles to Django.', null=True),
        ),
    ]
