# Generated by Django 4.2.15 on 2025-01-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersession'),
        ('core', '0003_preferences_spatial_reference_layer_max_area'),
    ]

    operations = [
    ]
