# Generated by Django 4.2.15 on 2025-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250113_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='analysis_state',
            field=models.JSONField(default=dict),
        ),
    ]
