# Generated by Django 4.2.20 on 2025-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_preferences_result_cache_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='max_wait_analysis_run_time',
            field=models.IntegerField(default=300, help_text='The maximum wait time in seconds for fetching analysis status.'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='spatial_reference_layer_max_area',
            field=models.IntegerField(default=500000000, help_text='The maximum area in square meters for spatial reference layer.'),
        ),
    ]
