# Generated by Django 4.2.20 on 2025-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_preferences_max_wait_analysis_run_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='number_of_decimal_places',
            field=models.IntegerField(default=2, help_text='The number of decimal places to show in the UI, e.g. table in Baseline Analysis results.'),
        ),
    ]
