# Generated by Django 4.2.23 on 2025-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_preferences_number_of_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='spatial_reference_layer_max_area',
            field=models.BigIntegerField(default=500000000, help_text='The maximum area in square meters for spatial reference layer.'),
        ),
    ]
