# Generated by Django 4.2.23 on 2025-08-22 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUploadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Name of the uploaded file.', max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size of the uploaded file in bytes.')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the file was uploaded.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the upload.', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Upload progress percentage.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the upload failed.', null=True)),
                ('session', models.CharField(help_text='Session ID for the upload.', max_length=255)),
                ('file_id', models.CharField(blank=True, help_text='File ID for the uploaded asset.', max_length=255, null=True)),
                ('upload_path', models.TextField(blank=True, help_text='Path where the file is uploaded.', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the asset.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Upload Item',
                'verbose_name_plural': 'Asset Upload Items',
                'ordering': ['-upload_date'],
            },
        ),
    ]
