# Generated by Django 4.2.28 on 2026-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_assetuploaditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemap',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
