site_name: Africa Rangeland Watch
site_description: "Project technical and user documentation."
site_author: "Kartoza"
docs_dir: ./src
site_dir: ./site
repo_name: "Africa Rangeland Watch"
repo_url: "https://github.com/kartoza/africa_rangeland_watch.git"
edit_uri: "https://github.com/kartoza/africa_rangeland_watch/tree/main/docs/"

copyright: Kartoza and Contributors

markdown_extensions:
        - attr_list # lets us resize images see https://github.com/mkdocs/mkdocs/issues/1678#issuecomment-455500757
        - sane_lists # needed to keep numbers in ordered lists correct
        - pymdownx.highlight:
                  anchor_linenums: true
        - pymdownx.inlinehilite
        #- mdx_truly_sane_lists
        - toc:
                  permalink: true
                   #slugify: !!python/name:pymdownx.slugs.slugify
        - pymdownx.snippets:
                  base_path: .
        - admonition
        - tables
        - pymdownx.details
        - pymdownx.caret
        - pymdownx.keys
        - pymdownx.mark
        - pymdownx.tilde
        - pymdownx.superfences:
                  custom_fences:
                          - name: mermaid
                            class: mermaid
                            format: !!python/name:pymdownx.superfences.fence_code_format
        - pymdownx.emoji:
                  emoji_index: !!python/name:material.extensions.emoji.twemoji
                  emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation
nav:
        - Home:
                  - Home: index.md
                  - Code of Conduct: about/code-of-conduct.md
                  - License: about/license.md
                  - Running Instances: about/running-instances.md
        - User:
                  - user/index.md
                  - Quickstart: user/quickstart/index.md
                  - Guide:
                          - user/guide/index.md
                          - Sign Up: user/guide/sign-up.md
                          - Sign In: user/guide/sign-in.md
                          - Sign Out Page: user/guide/Sign-out.md
                          - Sign Out From User Profile: user/guide/Sign-out-user-profile.md
                          - Forgot Password: user/guide/forgot-password.md
                          - About Page: user/guide/about.md
                          - Analysis Result Page: user/guide/Analysis-result.md
                          - Dashboard Page: user/guide/Dashboard.md
                          - Map Page: user/guide/map.md
                          - Notifications: user/guide/Notifications.md
                          - Organisation Information Page: user/guide/Organisation-information.md
                          - Support Page: user/guide/Support.md
                          - User Profile: user/guide/user-profile.md
                          - Update Profile: user/guide/update-profile.md
                          - Uploaded Resources Page: user/guide/Uploaded-resources.md
                          - Earthranger Events: user/guide/Earthranger-events.md
                          - Alert Settings: user/guide/Alertsettings.md
                  - Manual :
                          - user/manual/index.md
                          - Sign Up: user/manual/sign-up.md
                          - Sign In: user/manual/sign-in.md
                          - Sign Out Page: user/manual/Sign-out.md
                          - Sign Out From User Profile: user/manual/Sign-out-user-profile.md
                          - Forgot Password: user/manual/forgot-password.md
                          - About Page: user/manual/about.md
                          - Analysis Result Page: user/manual/Analysis-result.md
                          - Dashboard Page: user/manual/Dashboard.md
                          - Map Page: user/manual/map.md
                          - Notifications: user/manual/Notifications.md
                          - Organisation Information Page: user/manual/Organisation-information.md
                          - Support Page: user/manual/Support.md
                          - User Profile: user/manual/user-profile.md
                          - Update Profile: user/manual/update-profile.md
                          - Uploaded Resources Page: user/manual/Uploaded-resources.md
                          - Earthranger Events: user/manual/Earthranger-events.md
                          - Alert Settings: user/manual/Alertsettings.md
                  - Onboarding: user/onboard.md
        - Administrators:
                - administrator/index.md
                - Guide:
                        - administrator/guide/index.md
                - Manual:
                        - administrator/manual/index.md
        - Developers:
                - developer/index.md
                - Guide:
                        - developer/guide/index.md
                        - Architecture: developer/guide/architecture.md
                        - Prerequisites: developer/guide/prerequisites.md
                        - Cloning: developer/guide/cloning.md
                        - IDE Setup: developer/guide/ide-setup.md
                        - Configuration: developer/guide/configuration.md
                        - Building: developer/guide/building.md
                        - Design: developer/guide/design.md
                        - Road Map: developer/guide/roadmap.md
                        - Workflows: developer/guide/workflows.md
                        # Pages to render but exclude from navigation
                        - "": developer/guide/templates/pull-request-template.md 
                        - "": developer/guide/templates/commit-message-convention.md
                - Manual: developer/manual/index.md
                - Documentation Writing:
                        - developer/documentation/index.md
                        - Simple Workflow: developer/documentation/easy-workflow.md
                        - Advanced Workflow: developer/documentation/overview.md
                        - Context Help: developer/documentation/context-help.md
                - API:
                        - developer/api/index.md
                        - Reference: developer/api/manual/index.md
                        - Guide: developer/api/guide/index.md
                - License: about/license.md
        - DevOps:
                  - devops/index.md
                  - Guide: devops/guide/index.md
                  - Manual: devops/manual/index.md
        - About:
                  - About: about/index.md
                  - License: about/license.md
                  - Contributing: about/contributing.md
                  - Disclaimer: about/disclaimer.md


# Configuration
theme:
  name: material
  logo: img/arw-logo-1.svg
  language: en
  direction: ltr
  include_search_page: false
  search_index_only: true
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
#    - navigation.expand # This causes the nav menu to auto expand
    - navigation.indexes
    - navigation.instant
#    - navigation.sections # This removes the ability to shrink sections on the nav menu but gives the bold headings
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: grey
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  icon:
    logo: material/book

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kartoza
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kartoza/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KartozaGeo
    - icon: fontawesome/brands/facebook
      link: https://kartoza.com
    - icon: fontawesome/solid/earth-africa
      link: https://kartoza.com

extra_css:
  - css/print.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

# Needed for the hooks below to work
plugins:
  - search
  - mkdocs-video
  - mkdocstrings:
      handlers:
        python:
          paths: [../django_project]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            # Lots of other nice options can be found at  
            # https://mkdocstrings.github.io/python/usage/
            docstring_style: sphinx
            heading_level: 2
            show_bases: true
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            merge_init_into_class: true
            docstring_options:

  - redirects:
      redirect_maps:
        #see https://github.com/mkdocs/mkdocs-redirects/tree/master#using
        #'old.md': 'new.md'
        #'old/file.md': 'new/file.md'
        #'some_file.md': 'http://external.url.com/foobar'
  - enumerate-headings:
      toc_depth: 3
      strict: true
      increment_across_pages: true
      include:
        - "*"
      exclude:
        - index.md
        - user/index.md
        - administrator/index.md
        - developer/index.md
        - developer/manual/*.md
        - devops/index.md
      restart_increment_after:
        - second_section.md

# Hook to add a uuid to every anchor
# see also hook.py and https://github.com/squidfunk/mkdocs-material/discussions/3758#discussioncomment-4397373
# Note that although the above link implies you can use UUIDs, you have to use numeric IDS not UUIDS
hooks:
  - ./uuid_redirects_hook.py
  - ./python_manual_hook.py
